package view;


import javax.swing.*;
import java.io.File;
import controller.*;
import model.songData;


public class MainView extends javax.swing.JFrame {
    MPcontroller mp;
    private musicPlayer musicPlayer;
    
    public MainView() {
       
        initComponents();
        jButtonContinue.setVisible(false);
        jButtonContinue.setEnabled(false);
        mp = new MPcontroller(this);
        musicPlayer = new musicPlayer(mp);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton4 = new javax.swing.JButton();
        jFileChooser1 = new javax.swing.JFileChooser();
        jFileChooser2 = new javax.swing.JFileChooser();
        jFileChooser3 = new javax.swing.JFileChooser();
        jMenu1 = new javax.swing.JMenu();
        jScrollPane1 = new javax.swing.JScrollPane();
        jEditorPane1 = new javax.swing.JEditorPane();
        jPanel2 = new javax.swing.JPanel();
        jLabelJudul = new javax.swing.JLabel();
        jLabelArtis = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jSliderPlayBack = new javax.swing.JSlider();
        jLabelAkhir = new javax.swing.JLabel();
        jLabelAwal = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jButtonPause = new javax.swing.JButton();
        jButtonLoadSong = new javax.swing.JButton();
        jButtonContinue = new javax.swing.JButton();
        jButtonNext = new javax.swing.JButton();
        jButtonPrevious = new javax.swing.JButton();
        jButtonRepeat = new javax.swing.JButton();
        jButtonPlaylist = new javax.swing.JButton();
        jButtonEdit = new javax.swing.JButton();

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/next.png"))); // NOI18N
        jButton4.setBorderPainted(false);
        jButton4.setContentAreaFilled(false);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jMenu1.setText("jMenu1");

        jScrollPane1.setViewportView(jEditorPane1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));

        jLabelJudul.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabelJudul.setForeground(new java.awt.Color(255, 255, 255));
        jLabelJudul.setText("Song Tittle");

        jLabelArtis.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabelArtis.setForeground(new java.awt.Color(255, 255, 255));
        jLabelArtis.setText("Artist");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/cover.png"))); // NOI18N

        jSliderPlayBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jSliderPlayBackMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jSliderPlayBackMouseReleased(evt);
            }
        });

        jLabelAkhir.setForeground(new java.awt.Color(255, 255, 255));
        jLabelAkhir.setText("akhir");

        jLabelAwal.setForeground(new java.awt.Color(255, 255, 255));
        jLabelAwal.setText("awal");

        jPanel1.setBackground(new java.awt.Color(0, 153, 0));

        jButtonPause.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/pause.png"))); // NOI18N
        jButtonPause.setBorderPainted(false);
        jButtonPause.setContentAreaFilled(false);
        jButtonPause.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPauseActionPerformed(evt);
            }
        });

        jButtonLoadSong.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/burger.png"))); // NOI18N
        jButtonLoadSong.setBorderPainted(false);
        jButtonLoadSong.setContentAreaFilled(false);
        jButtonLoadSong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLoadSongActionPerformed(evt);
            }
        });

        jButtonContinue.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/play.png"))); // NOI18N
        jButtonContinue.setBorderPainted(false);
        jButtonContinue.setContentAreaFilled(false);
        jButtonContinue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonContinueActionPerformed(evt);
            }
        });

        jButtonNext.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/next.png"))); // NOI18N
        jButtonNext.setBorderPainted(false);
        jButtonNext.setContentAreaFilled(false);
        jButtonNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNextActionPerformed(evt);
            }
        });

        jButtonPrevious.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/previous.png"))); // NOI18N
        jButtonPrevious.setBorderPainted(false);
        jButtonPrevious.setContentAreaFilled(false);
        jButtonPrevious.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPreviousActionPerformed(evt);
            }
        });

        jButtonRepeat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/repeat.png"))); // NOI18N
        jButtonRepeat.setBorderPainted(false);
        jButtonRepeat.setContentAreaFilled(false);
        jButtonRepeat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRepeatActionPerformed(evt);
            }
        });

        jButtonPlaylist.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/next.png"))); // NOI18N
        jButtonPlaylist.setBorderPainted(false);
        jButtonPlaylist.setContentAreaFilled(false);
        jButtonPlaylist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPlaylistActionPerformed(evt);
            }
        });

        jButtonEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/next.png"))); // NOI18N
        jButtonEdit.setBorderPainted(false);
        jButtonEdit.setContentAreaFilled(false);
        jButtonEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addComponent(jButtonPrevious)
                .addGap(18, 18, 18)
                .addComponent(jButtonContinue)
                .addGap(20, 20, 20)
                .addComponent(jButtonPause)
                .addGap(18, 18, 18)
                .addComponent(jButtonNext)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jButtonRepeat)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonLoadSong))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jButtonEdit)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonPlaylist)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonLoadSong)
                    .addComponent(jButtonRepeat))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButtonPause, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jButtonContinue, javax.swing.GroupLayout.Alignment.TRAILING)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addComponent(jButtonNext)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonPrevious)
                        .addGap(33, 33, 33)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtonPlaylist)
                    .addComponent(jButtonEdit)))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(153, 153, 153)
                .addComponent(jLabelArtis)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSliderPlayBack, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabelAwal)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabelAkhir))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(130, 130, 130)
                                .addComponent(jLabelJudul))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(63, 63, 63)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 65, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabelJudul, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelArtis)
                .addGap(48, 48, 48)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                .addComponent(jSliderPlayBack, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelAkhir)
                    .addComponent(jLabelAwal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButtonEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditActionPerformed
        // TODO add your handling code here:
        PlaylistEdit playlist = new PlaylistEdit();
        playlist.setVisible(true);
    }//GEN-LAST:event_jButtonEditActionPerformed

    private void jButtonPlaylistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPlaylistActionPerformed
        Playlist playlist = new Playlist();
        playlist.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonPlaylistActionPerformed

    private void jButtonRepeatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRepeatActionPerformed
        mp.toggleRepeatMode();
        if (mp.isRepeatMode())
        System.out.println("repeat mode on");
        else
        System.out.println("repeat mode off");
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonRepeatActionPerformed

    private void jButtonPreviousActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPreviousActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonPreviousActionPerformed

    private void jButtonNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonNextActionPerformed

    private void jButtonContinueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonContinueActionPerformed

        mp.enablePlayButtonDisablePauseButton();
        musicPlayer.playCurrentSong();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonContinueActionPerformed

    private void jButtonLoadSongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLoadSongActionPerformed
        mp.setfileChooser();
        int result = jFileChooser1.showOpenDialog(MainView.this);
        File selectedFile = jFileChooser1.getSelectedFile();

        // this means that we are also checking to see if the user pressed the "open" button
        if(result == JFileChooser.APPROVE_OPTION && selectedFile != null){
            // create a song obj based on selected file
            songData song = new songData(selectedFile.getPath());

            System.out.println("selectedfile" + selectedFile);
            System.out.println("song" + song);
            // load song in music player
            if (musicPlayer != null) {
                musicPlayer.loadSong(song);

                // update song title and artist
                mp.updateSongTitleAndArtist(song);

                // update playback slider
                mp.updatePlaybackSlider(song);

                // toggle on pause button and toggle off play button
                mp.enablePlayButtonDisablePauseButton();
            } else {
                System.err.println("musicPlayer is not initialized.");
            }

            // toggle on pause button and toggle off play button
            //                    enablePauseButtonDisablePlayButton();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonLoadSongActionPerformed

    private void jButtonPauseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPauseActionPerformed

        musicPlayer.pauseSong();
        mp.enablePauseButtonDisablePlayButton();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonPauseActionPerformed

    private void jSliderPlayBackMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jSliderPlayBackMouseReleased
        JSlider source = (JSlider) evt.getSource();
        System.out.println("source" + source);
        // get the frame value from where the user wants to playback to
        int frame = source.getValue();
        System.out.println("frame" + frame);
        // update the current frame in the music player to this frame
        musicPlayer.setCurrentFrame(frame);

        // update current time in milli as well
        musicPlayer.setCurrentTimeInMilli((int) (frame / (2.08 * musicPlayer.getCurrentSong().getFrameRatePerMilliseconds())));

        // resume the song
        musicPlayer.playCurrentSong();

        // toggle on pause button and toggle off play button
        mp.enablePlayButtonDisablePauseButton();
        // TODO add your handling code here:
    }//GEN-LAST:event_jSliderPlayBackMouseReleased

    private void jSliderPlayBackMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jSliderPlayBackMousePressed
        musicPlayer.pauseSong();
        // TODO add your handling code here:
    }//GEN-LAST:event_jSliderPlayBackMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButtonContinue;
    private javax.swing.JButton jButtonEdit;
    private javax.swing.JButton jButtonLoadSong;
    private javax.swing.JButton jButtonNext;
    private javax.swing.JButton jButtonPause;
    private javax.swing.JButton jButtonPlaylist;
    private javax.swing.JButton jButtonPrevious;
    private javax.swing.JButton jButtonRepeat;
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JFileChooser jFileChooser2;
    private javax.swing.JFileChooser jFileChooser3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelAkhir;
    private javax.swing.JLabel jLabelArtis;
    private javax.swing.JLabel jLabelAwal;
    private javax.swing.JLabel jLabelJudul;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSlider jSliderPlayBack;
    // End of variables declaration//GEN-END:variables
    
    
    public JFileChooser getjFileChooser1() {
        return jFileChooser1;
    }

    public void setjFileChooser1(JFileChooser jFileChooser1) {
        this.jFileChooser1 = jFileChooser1;
    }

    public JSlider getjSliderPlayBack() {
        return jSliderPlayBack;
    }

    public void setjSliderPlayBack(JSlider jSliderPlayBack) {
        this.jSliderPlayBack = jSliderPlayBack;
    }

    public JLabel getjLabelArtis() {
        return jLabelArtis;
    }

    public void setjLabelArtis(JLabel jLabelArtis) {
        this.jLabelArtis = jLabelArtis;
    }

    public JLabel getjLabelJudul() {
        return jLabelJudul;
    }

    public void setjLabelJudul(JLabel jLabelJudul) {
        this.jLabelJudul = jLabelJudul;
    }

    public JLabel getjLabelAkhir() {
        return jLabelAkhir;
    }

    public void setjLabelAkhir(JLabel jLabelAkhir) {
        this.jLabelAkhir = jLabelAkhir;
    }

    public JLabel getjLabelAwal() {
        return jLabelAwal;
    }

    public void setjLabelAwal(JLabel jLabelAwal) {
        this.jLabelAwal = jLabelAwal;
    }

    public JButton getjButtonContinue() {
        return jButtonContinue;
    }

    public void setjButtonContinue(JButton jButtonContinue) {
        this.jButtonContinue = jButtonContinue;
    }

    public JButton getjButtonPause() {
        return jButtonPause;
    }

    public void setjButtonPause(JButton jButtonPause) {
        this.jButtonPause = jButtonPause;
    }
}
